FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN ./node_modules/.bin/sass src/styles/main.scss src/styles/main.css
RUN npx tsc
EXPOSE 3000
RUN npm install -g serve
CMD ["serve", "-s", ".", "-l", "3000"]